[package]
name = "batcher"
version = "0.1.0"
edition = "2021"
description = "A very basic batching library"
github= "https://github.com/incaw/batcher"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]